[package]
name = "popoen"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9"
spin = "0.10.0"
x86_64 = "0.15.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
